media: assets/images
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [title, date, categories, tags, comments  ]
    fields:
      - { name: published, label: Published , type: boolean , default: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Date, type: date }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: comments, label: Comments, type: boolean, default: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }