media:
  input: assets/images
  output: /assets/images

content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [title, date, category, tags, description, comments, pin, published, image, author]
    fields:
    
      - name: title
        label: Title
        type: string
        required: true
        
      - name: date
        label: Date
        type: date
        options:
         time: true
         format: yyyy-MM-dd HH:mm +600
        required: true
         
      - name: categories
        label: Categories
        type: select
        options:
          values:
            - value: Miscellaneous
              label: Miscellaneous
            - value: Subscriptions
              label: Subscriptions
            - value: Tutorials 
              label: Tutorials
        

      - name: tags
        label: Tags
        type: select
        options:
          values:
            - value: tanmoythebot
              label: tanmoythebot
            - value: tanmoy
              label: tanmoy
            - value: tutorials 
              label: tutorials
        
              
      - name: author
        label: Author
        type: select
        options:
          values:
            - value: tanmoythebot
              label: TanmoyTheBoT
            - value: patricia
              label: Patricia Wills
            - value: alice
              label: Alice Brown
        required: true
        
      - name: description
        label: Description
        type: string
        options:
          maxlength: 160

      - name: image
        label: Image
        type: image
          


      - name: published
        label: Published
        type: boolean
        default: true   
        
      - name: pin
        label: Pin Post
        type: boolean
        default: false  

      - name: comments
        label: Comments
        type: boolean
        default: false 

      - name: body
        label: Body
        type: rich-text




  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
        required: true
        default: "Chirpy"
        
      - name: description
        label: Website description
        type: string
        description: "Will be provided for any page with no description."
        required: true
        default: "A minimal, responsive and feature-rich Jekyll theme for technical writing."
        
      - name: url
        label: Website URL
        type: string
        pattern: "^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$"
        required: true
        default: "https://TanmoyTheBoT.github.io"
        
      - name: cover
        label: Preview image
        type: image
        description: "Image used in the social preview on social networks (e.g., Facebook, Twitter...)"
        required: true
        default: "https://tanmoy.xyz/assets/images/avatar.jpg"
        
      - name: theme
        label: Theme
        type: string
        default: "jekyll-theme-chirpy"
        
      - name: lang
        label: Language
        type: string
        default: "en"
        
      - name: timezone
        label: Timezone
        type: string
        default: "Asia/Dhaka"
        
      - name: github_username
        label: GitHub Username
        type: string
        required: true
        default: "github_username"
        
      - name: twitter_username
        label: Twitter Username
        type: string
        required: true
        default: "twitter_username"
        
      - name: social_name
        label: Social Name (Full Name)
        type: string
        required: true
        default: "Your Full Name"
        
      - name: social_email
        label: Social Email
        type: string
        required: true
        default: "example@domain.com"
        
      - name: social_links
        label: Social Links
        type: array
        items:
          type: string
        default:
          - "https://twitter.com/username"
          - "https://github.com/username"
        
      - name: webmaster_verifications
        label: Webmaster Verifications
        type: object
        properties:
          google:
            label: Google Verification Code
            type: string
          bing:
            label: Bing Verification Code
            type: string
          alexa:
            label: Alexa Verification Code
            type: string
          yandex:
            label: Yandex Verification Code
            type: string
          baidu:
            label: Baidu Verification Code
            type: string
          facebook:
            label: Facebook Verification Code
            type: string
        
      - name: analytics
        label: Web Analytics
        type: object
        properties:
          google:
            label: Google Analytics ID
            type: string
          goatcounter:
            label: GoatCounter ID
            type: string
          umami:
            label: Umami ID
            type: string
            domain:
              label: Umami Domain
              type: string
          matomo:
            label: Matomo ID
            type: string
            domain:
              label: Matomo Domain
              type: string
          cloudflare:
            label: Cloudflare Web Analytics Token
            type: string
          fathom:
            label: Fathom Site ID
            type: string
        
      - name: pwa
        label: PWA Configuration
        type: object
        properties:
          enabled:
            label: Enable PWA
            type: boolean
            default: false
          cache:
            label: Enable Offline Cache
            type: boolean
            default: true
            deny_paths:
              label: Denied Cache Paths
              type: array
              items:
                type: string
        
      - name: paginate
        label: Pagination
        type: number
        default: 10
        
      - name: baseurl
        label: Base URL
        type: string
        default: "/chirpy"

      - name: toc
        label: Table of Contents
        type: boolean
        default: true
        
      - name: comments
        label: Comments
        type: object
        properties:
          provider:
            label: Comments Provider
            type: string
            options:
              - disqus
              - utterances
              - giscus
            default: ""
          
      - name: assets
        label: Self-hosted Static Assets
        type: object
        properties:
          self_host:
            label: Enable Static Asset Hosting
            type: boolean
            default: false
          env:
            label: Environment
            type: string
            options:
              - development
              - production
        
      - name: sass
        label: Sass Configuration
        type: object
        properties:
          style:
            label: Sass Style
            type: string
            options:
              - compressed
              - expanded
            default: "compressed"
        
      - name: exclude
        label: Excluded Files and Folders
        type: array
        items:
          type: string
        default:
          - "*.gem"
          - "*.gemspec"
          - "docs"
          - "tools"
          - "README.md"
          - "LICENSE"
        
      - name: jekyll_archives
        label: Jekyll Archives Settings
        type: object
        properties:
          enabled:
            label: Enabled Archives
            type: array
            items:
              type: string
            default:
              - categories
              - tags
          layouts:
            label: Layouts for Archives
            type: object
            properties:
              category:
                label: Category Layout
                type: string
                default: "category"
              tag:
                label: Tag Layout
                type: string
                default: "tag"
          permalinks:
            label: Permalink Patterns
            type: object
            properties:
              tag:
                label: Tag Permalink Pattern
                type: string
                default: "/tags/:name/"
              category:
                label: Category Permalink Pattern
                type: string
                default: "/categories/:name/"

